services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: echo_notify
      POSTGRES_USER: echo
      POSTGRES_PASSWORD: echo
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:3.7
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-init-topics:
    image: bitnami/kafka:3.7
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "/scripts/init-topics.sh"]
    volumes:
      - ./docker/kafka/init-topics.sh:/scripts/init-topics.sh

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"

  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "16686:16686"
      - "4317:4317"

  prometheus:
    image: prom/prometheus:v2.53.1
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.4
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards

  echo-notify-api:
    build:
      context: .
      dockerfile: echo-notify-api/Dockerfile
    depends_on:
      - postgres
      - kafka
    ports:
      - "8080:8080"

  echo-notify-consumer:
    build:
      context: .
      dockerfile: echo-notify-consumer/Dockerfile
    depends_on:
      - postgres
      - kafka

  echo-notify-worker:
    build:
      context: .
      dockerfile: echo-notify-worker/Dockerfile
    depends_on:
      - postgres
      - kafka
