global:
  scrape_interval: 10s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: echo-notify-api
    static_configs:
      - targets: ["echo-notify-api:8080"]
    metrics_path: /metrics

  - job_name: echo-notify-consumer
    static_configs:
      - targets: ["echo-notify-consumer:8081"]
    metrics_path: /metrics

  - job_name: echo-notify-worker
    static_configs:
      - targets: ["echo-notify-worker:8082"]
    metrics_path: /metrics
